# [[plugins]]
# repo  = 'stephpy/vim-yaml'
# on_ft = ['yaml']

[[plugins]]
repo  = 'fatih/vim-go'
on_ft = ['go']

# [[plugins]]
# repo  = 'jmcantrell/vim-virtualenv'
# on_ft = ['python']

[[plugins]]
repo  = 'zchee/deoplete-jedi'
on_ft = ['python']

[[plugins]]
repo  = 'mattn/emmet-vim'
on_ft = ['html', 'css']

[[plugins]]
repo  = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo  = 'pangloss/vim-javascript'
on_ft = ['javascript']

# [[plugins]]
# repo  = 'mhartington/nvim-typescript'
# on_ft = ['typescript']

[[plugins]]
repo  = 'leafgarland/typescript-vim'
on_ft = ['typescript']

# [[plugins]]
# repo  = 'Quramy/tsuquyomi'
# on_ft = ['typescript']
# build = 'make -f make_mac.mak'

[[plugins]]
repo  = 'Shougo/deoplete-rct'
on_ft = ['ruby']

[[plugins]]
repo  = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo  = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
